const postsData = [
    {
        id:1,
        title:"My trip to Paris",
        date:"July 26, 2019",
        сategory1: "Travels",
        сategory2: ' • Lifestyle',
        image:"/images/postsimg/lisbeth-demo1-2.3-390x240.jpg",
        imagesmall:'',
        likes:23,
        excerpt:"Paris is the capital and most populous city of France, with an administrative limits area of 105 square kilometres (41 square miles) and a 2015 population of 2,229,621. The...",           
    },
    {
        id:2,
        title:"Why do we think cats are unfriendly?",
        date:"September 01, 2019",
        сategory1: 'Blog',
        сategory2: ' • Lifestyle',
        image:"/images/postsimg/lisbeth-demo1-9g-390x240.jpg",
        imagesmall:'',
        likes:45,
        excerpt:"Cats are the only asocial animal we have successfully domesticated. We’re disappointed that we don’t bond with them as easily as dogs. But are we just missing the signs?",   

    
    },
    {
        id:3,
        title:"Best coffee in town",
        date:"September 24, 2019",
        сategory1: "Blog",
        сategory2: ' • Lifestyle',
        image:"/images/postsimg/anariel-post-15-390x240.jpg",
        imagesmall:'',
        likes:31,
        excerpt:"Over the past few years there have been a wave of independent coffee shops opening in town, which means caffeine lovers have more places than ever...",         
    },
    {
        id:4,
        title:"Visit the gardens",
        date:"October 18, 2019",
        сategory1: 'Blog',
        сategory2: ' • Travels',
        image:"/images/postsimg/anariel-post-13-390x240.jpg",
        imagesmall:'',
        likes:40,
        excerpt:"Visit the world's largest glass greenhouse where stunning flower displays and plant varieties await...",        
    },
    {
        id:5,
        title:"Come with me on a drive to the country",
        date:"October 30, 2019",
        сategory1: 'Travels',
        сategory2: ' • Lifestyle',
        image:"/images/postsimg/anariel-post-1-390x240.jpg",
        imagesmall:'',
        likes:9,
        excerpt:"I got used to travelling by car a lot and it was very hard for me to dare to travel without it. This article is about advantages of travelling by car...",        
    },
    {
        id:6,
        title:"Fashion tips for autumn days",
        date:"November 23, 2019",
        сategory1: 'Blog',
        сategory2: ' • Fashion',
        image:"/images/postsimg/anariel-post-12-390x240.jpg",
        imagesmall:'',
        likes:11,
        excerpt:"Fall is a versatile season for fashion. The weather starts getting cooler, making heavier-knit fabrics, boots, and chunky accessories in vogue. The...",        
    },
    {
        id:7,
        title:"Beautiful view from my home office",
        date:"December 12, 2019",
        сategory1: 'Blog',
        сategory2: ' • Travels',
        сategory3max: ' • Lifestyle',
        image:"/images/postsimg/anariel-post-10-390x240.jpg",
        imagesmall:'/images/postsimg/anariel-post-10-255x170.jpg',
        likes:68,
        excerpt:"To be successful, a home office needs to be both functional and efficient. You are going to be working in this environment...",      
    },
    {
        id:8,
        title:"Ten tips for travel by car",
        date:"December 30, 2019",
        сategory1: 'Travels',
        image:"/images/postsimg/anariel-post-4-390x240.jpg",
        imagesmall:"/images/postsimg/anariel-post-4-255x170.jpg",
        likes:52,
        excerpt:"So many people fly everywhere these days that you might think the classic road trip is a thing of the past. This is not actually the case...",          
    },
    {
        id:9,
        title:"Beautiful Christmas decoration",
        date:"Februery 02, 2020",
        сategory1: 'Blog',
        сategory2: ' • Fashion',
        image:"/images/postsimg/anariel-post-3-390x240.jpg",
        imagesmall:"/images/postsimg/anariel-post-3-255x170.jpg",
        likes:47,
        excerpt:"The holidays are perfect for spending time with loved ones and eating delicious food. You can easily spread the holiday cheer this season by embellishing your home with Christmas decorations.",          
    },
    {
        id:10,
        title:"Enjoy the winter time in the city",
        date:"Februery 14, 2020",
        сategory1: "Blog",
        сategory2: ' • Lifestyle',
        image:"/images/postsimg/anariel-post-11-390x240.jpg",
        imagesmall:"/images/postsimg/anariel-post-11-255x170.jpg",
        likes:49,
        excerpt:"Buying pieces of jewelry can be pretty expensive, even if it’s just costume jewelry. However, crafting handmade jewelry can mean much more...",     
    },
]

export default postsData